#server:
#  port: 8080
#
#spring:
#  application:
#    name: gateway
#  cloud:
#    gateway:
#      routes:
#        - id: dogModule
#          uri: http://localhost:8762/
#          predicates:
#            - Path=/animals/**
#        - id: secondModule
#          uri: http://localhost:8763/
#          predicates:
#            - Path=/second/**
